### ISSUE TITLE
[DFD playbook] Style footer links to be distinctively linky

### ISSUE THREAD

**Issue by daguar** [codeforamerica/codeforamerica.org#1016]
cc @danhon @dschrimmer Sweet demo!

A minor suggested improvement — the bottom bar's links are styled the same as text, so it wasn't visually clear to me that I could/should click them:

![screen shot 2015-04-08 at 12 24 02 pm](https://cloud.githubusercontent.com/assets/994938/7053468/36086ae4-ddea-11e4-98b9-76b484be986c.png)

https://www.codeforamerica.org/our-work/initiatives/digitalfrontdoor/playbook/user-needs/goals-good-city-website.html

**Comment by davidrleonard** [comment]
They're more link-y now.
