### ISSUE TITLE
DFD Landing: button styles broken

### ISSUE THREAD

**Issue by mollymcleod** [codeforamerica/codeforamerica.org#1017]
On rollover state, the buttons lose rounded corners and have some other weird styling. This is in both Chrome and Firefox.

![image](https://cloud.githubusercontent.com/assets/4099343/7054882/965a5394-ddf4-11e4-8feb-f2b8f5f2cb4d.png)

**Comment by davidrleonard** [comment]
Solved in codeforamerica/pattern-library#4.
