### ISSUE TITLE
2016 Wufoo Interest form

### ISSUE THREAD

**Issue by beccablazak** [codeforamerica/codeforamerica.org#1031]
@davidrleonard have gotten a couple interest forms from wufoo for the fellowship coming through my inbox. Any idea how folks would still be finding a the wufoo form rather than the updated google form?

**Comment by davidrleonard** [comment]
There were some old links around that might have been causing the problem, I directed those to the new form. 

You might also want to edit that form to take out the fields and put text/a link sending people to the new form, incase it's showing up in google searches or linked from off-site.

**Comment by Jaime-Alexis** [comment]
@beccablazak just making sure you saw @davidrleonard's note...
