### ISSUE TITLE
engagementcommons.org goes to a 404 CFA page

### ISSUE THREAD

**Issue by skorasaurus** [codeforamerica/codeforamerica.org#1035]
Found that engagementcommons.org redirects to http://www.codeforamerica.org/engagement-commons//apps which is a 404 page.

**Comment by migurski** [comment]
Where did you find the link?

**Comment by skorasaurus** [comment]
I've been going back and reading over mark headd's old blog posts and found it [here](http://civic.io/2012/06/20/open-gov-whats-gone-right-whats-gone-wrong/)

Sorry if this is the wrong repo or irrelevant, I'd figured you'd like to know that a domain that CFA-owned domain/project unintentionally redirects to a CFA 404.

**Comment by migurski** [comment]
Thanks—it’s not unintentional, and this is a fine place to raise the question! We’ve been taking down the various "commons" websites.
