### ISSUE TITLE
Broken style guide navigation

### ISSUE THREAD

**Issue by fuselagetown** [codeforamerica/codeforamerica.org#1039]
First of all, I love your style guide. I keep going back to it to find out what is best practice for style guides.

I've noticed that the navigation on the style guide is broken, the path on the links go to _site  before the path. Would you like me to fix it and submit a PO?

All the best,
Torunn

**Comment by davidrleonard** [comment]
Thanks for pointing this out, @fuselagetown. It had been stuck in my todo list for too long. It's fixed in codeforamerica/pattern-library#3, which is now live.

Glad to hear you're finding our format useful. Feedback is always welcome -- let me know if you have any suggestions for improvement.
