### ISSUE TITLE
Governments: apply to be a fellow edits

### ISSUE THREAD

**Issue by ZoeBlumenfeld** [codeforamerica/codeforamerica.org#1068]
@davidrleonard @Jaime-Alexis: edits to this page [http://www.codeforamerica.org/governments/]

1) move red block of text below "get involved"
2) in "get involved - for governments" add application is closed copy; replace "enlist" with "express interest for 2017" and link to "governments/fellowship-partner"

**Comment by davidrleonard** [comment]
Looks good, minus "express interest" wording
