### ISSUE TITLE
Governments-fellowship: apply to be a fellow edits

### ISSUE THREAD

**Issue by ZoeBlumenfeld** [codeforamerica/codeforamerica.org#1069]
@davidrleonard @Jaime-Alexis edits to [http://www.codeforamerica.org/governments/fellowship/]

1) change headline copy: "Express Interest to be a 2017 Fellowship Partner"
2) add copy right below header and before video: "Applications for the 2016 fellowship partnership are now closed.  Contact Luke Norris, Director of Government Relations, to discuss the 2017 fellowship program: luke[at]codeforamerica.org or call 816-200-8925."
3) add footer

**Comment by davidrleonard** [comment]
1) know we're trying to avoid using apply, but could we tighten this phrase up? people don't "express interest" ... another term?
2) cool
3) cool
