### ISSUE TITLE
Inconsistent staff data

### ISSUE THREAD

**Issue by wpietri** [codeforamerica/codeforamerica.org#1077]
Hi! I wrote a little program to make flashcards of the staff. In doing so, I noticed some inconsistent data. Here's my program's output:

    Missing from staff page: alex-tran.html
    Missing from staff page: ashley-meyers.html
    Missing from staff page: bob-sofman.html
    Missing from staff page: dana-oshiro.html
    Missing from staff page: erica-kwan.html
    Missing from staff page: lauren-reid.html
    Missing from staff page: mettabel-law.html
    Missing from staff page: michael-santus.html
    Missing from staff page: ron-bouganim.html

    Missing staff tag: alan-williams.html
    Missing staff tag: dave-guarino.html
    Missing staff tag: jacob-solomon.html
    Missing staff tag: molly-mcleod.html

The first group is people who are tagged as staff but who are not on the staff page. The latter group is people who are on the staff page but not tagged as staff. From spot checking, I suspect the fix for the former is to delete those files, or possibly to remove the "STAFF" tag. I think the fix for the latter is to add "STAFF" to the "MEMBER OF" section.

**Comment by Jaime-Alexis** [comment]
Yes the former are no longer staff (and Ron never was).

--------------------------------------------------------------------------------------------------------------------------------
Jaime-Alexis Fowler | Director of Marketing | *Code for America*
<http://codeforamerica.org/> | p:*214.673.9060* | @JaimeAlexis
<http://www.twitter.com/JaimeAlexis>

*Use your skills for good. **Apply to be a 2016 Code for America fellow.
<http://www.codeforamerica.org/forms/fellowship/become-a-fellow/?source_codes=staff>*
