### ISSUE TITLE
Navigation and headers break when resizing between mobile and desktop in browser window.

### ISSUE THREAD

**Issue by norrishung** [codeforamerica/codeforamerica.org#1079]
Jack discovered this today and I just wanted to log it since I couldn't find it mentioned anywhere.

When resizing from desktop to mobile width on a desktop browser, the desktop navigation is still shown (and looks broken) and the mobile navigation isn't present. The desktop navigation also obscures the hero images. The reverse problem is true when you resize from mobile to desktop widths.

I imagine that we want this transition to be handled more elegantly in the future.

![screen shot 2015-05-04 at 10 42 41 am](https://cloud.githubusercontent.com/assets/606439/7458581/5647ad3c-f24a-11e4-9f4c-a0bc4be31df2.png)
![screen shot 2015-05-04 at 10 42 29 am](https://cloud.githubusercontent.com/assets/606439/7458582/5647a4b8-f24a-11e4-9ef0-62e4ec5cf6df.png)

**Comment by migurski** [comment]
We talked about this Clearleft when they did the work, and their explanation was that in their experience, the only people they ever observed resizing a window were web designers checking responsive behaviors. :)

**Comment by davidrleonard** [comment]
Agreed with migurski. The solution isn't perfect but it performs really well across browsers. Don't think it's a bug. 

David
