### ISSUE TITLE
Redirect Civic Engagement standard to codeforamerica.org/engagment

### ISSUE THREAD

**Issue by prestonrhea** [codeforamerica/codeforamerica.org#1103]
Currently there is no page at http://www.codeforamerica.org/engagement. The Civic Engagement Standard is at https://www.codeforamerica.org/governments/principles/engagement/, and it's not linked from any other pages - you reach it by typing it in directly.

Can we change this page to be housed at the shorter URL? It will help us to share it out and put it in publications. If there is a better way that @danhon recommends for content standards I'm all for it.

cc @dschrimmer

**Comment by migurski** [comment]
For short, easy-to-share URLs like this I think what you really want is a bitly link, like this: http://c4a.me/engagement

**Comment by danhon** [comment]
Also I believe the engagement standard is linked to from the 21c principles.
