### ISSUE TITLE
Brigade map not obviously linked

### ISSUE THREAD

**Issue by bennovack** [codeforamerica/codeforamerica.org#1126]
The "Brigade" link in the navbar of the site links to /brigade/about, not /brigade/. From my cursory scanning, nothing on the main CfA page links to the brigade map directly. How is a visitor supposed to find it? The "About" page similarly refers to starting a new brigade if there's none nearby - but doesn't then link to the map so someone might find that nearby brigade.

**Comment by davidrleonard** [comment]
We're now linking to the Brigade map with "Volunteer for your community" in the footer and under the "What You Can Do" section. See #1477.
