### ISSUE TITLE
Multiple brigade "About" sections

### ISSUE THREAD

**Issue by bennovack** [codeforamerica/codeforamerica.org#1133]
http://www.codeforamerica.org/brigade/about/

http://www.codeforamerica.org/about/brigade/

These paths lead to different pages, with different copy, and do not link to one another.

**Comment by davidrleonard** [comment]
Thanks for the report, @bennovack. We no longer link to the /about/brigade page anywhere, and are phasing that out of existence in favor of brigade/about
