### ISSUE TITLE
Library pages look funky (in a bad way)

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/codeforamerica.org#1135]
See http://www.codeforamerica.org/library/category/About+Code+for+America
![screen shot 2015-06-01 at 10 44 53 pm](https://cloud.githubusercontent.com/assets/2533112/7929237/77ffbc54-08b0-11e5-9ade-607b689e56c2.png)

Looks like it has something to do with:
`Failed to load resource: the server responded with a status of 404 (Not Found)
global.js:75`
`Uncaught TypeError: Cannot read property 'offsetHeight' of null`

cc @ladyson and h/t Kakul for noticing.

**Comment by davidrleonard** [comment]
The library is dead now. :(
