### ISSUE TITLE
Jen's TED talk video displaying incorrectly

### ISSUE THREAD

**Issue by MissPaaj** [codeforamerica/codeforamerica.org#1157]
The video on http://www.codeforamerica.org/blog/2012/03/08/jennifer-pahlka-at-ted-video/ looks like it's cut in half. Seeing problem in both FF & Chrome.
![screen shot 2015-06-24 at 4 43 24 pm](https://cloud.githubusercontent.com/assets/7319955/8343977/2afb0106-1a90-11e5-8dcc-4121decbb7ef.png)

**Comment by kcunanan** [comment]
Hi MissPaaj,

I can't find access to the blogs folder on the codeforamerica.org master site. BUT, I did figure out the problem. Do you know where I can get access HTML for the blogs? If not, it's an easy fix. Let me know, thanks!

**Comment by davidrleonard** [comment]
Thanks for the bug repor, this is fixed.
