### ISSUE TITLE
Anon feedback form?

### ISSUE THREAD

**Issue by danhon** [codeforamerica/codeforamerica.org#1252]
Someone asked for a way to provide anonymous feedback to the gov tech procurement playbook. Do we have a way to do that? If so, lmk where the form lives and the arguments and I can include it in the resource layout.

**Comment by davidrleonard** [comment]
@danhon Going back through old issues, I'm not sure an anon feedback form is high priority for us right now. I'd recommend people go through email (info@codeforamerica.org is at the bottom of every page) or Github; not anon, unfortunately, but seems to work for us pretty well.
