### ISSUE TITLE
Library link in nav

### ISSUE THREAD

**Issue by pahlkadot** [codeforamerica/codeforamerica.org#1297]
I think we decided to toast the library?  It still shows up in the nav on http://www.codeforamerica.org/our-work/

**Comment by davidrleonard** [comment]
Thanks Jen, on it.

**Comment by davidrleonard** [comment]
This if fixed in #1299. Thanks for the bug.

**Comment by pahlkadot** [comment]
Thank you!!!

On Tue, Aug 25, 2015 at 4:36 PM, David Leonard <notifications@github.com>
wrote:

> Closed #1297
> <https://github.com/codeforamerica/codeforamerica.org/issues/1297>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/codeforamerica.org/issues/1297#event-392262072>
> .
>



-- 
*Register for the Code for America Summit
<http://www.codeforamerica.org/summit/> in Oakland, CA, Sept 30th - Oct
2nd.*

Jennifer Pahlka
mobile: 415 420 2933
@pahlkadot
