### ISSUE TITLE
Fix donor logos

### ISSUE THREAD

**Issue by mattboitan0** [codeforamerica/codeforamerica.org#1325]
Hey @davidrleonard can you help with this quick fix? 

http://107.170.241.55/codeforamerica/codeforamerica.org/9-2-donor-logos/index.html

I'm trying to get the 3 donor logos at the bottom to show up but something's messed up. Thanks!

**Comment by davidrleonard** [comment]
https://jekit.codeforamerica.org/codeforamerica/codeforamerica.org/9-2-donor-logos/index.html

They look OK to me. Let me know if there is something I'm missing. Closing this.
