### ISSUE TITLE
jack-madans.jpg and patrick-hammons.jpg === 404

### ISSUE THREAD

**Issue by creade** [codeforamerica/codeforamerica.org#1326]
![image](https://cloud.githubusercontent.com/assets/356576/9611872/07289558-5097-11e5-9a74-f3f8861028c3.png)
jack-madans.jpg and patrick-hammons.jpg both 404 on the summit page

**Comment by davidrleonard** [comment]
Fixed a bit back. Thanks for flagging for us!
