### ISSUE TITLE
Summit 2015 Schedule - Printer-friendly version

### ISSUE THREAD

**Issue by Judy5000** [codeforamerica/codeforamerica.org#1345]
A printer-friendly version of the schedule is good practice for accessibility. Thanks.

**Comment by davidrleonard** [comment]
Please find a print 2015 Schedule copy attached to this Issue. Thanks.

[cfasummit-program2015-print.pdf](https://github.com/codeforamerica/codeforamerica.org/files/13549/cfasummit-program2015-print.pdf)
