### ISSUE TITLE
Category CSS on /blog is messed up

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/codeforamerica.org#1361]
When on the /blog front page, the categories for each post are messed up.

Looks like it may be some weird setting with `ul class="post-categories"`

![screen shot 2015-09-14 at 3 46 35 pm](https://cloud.githubusercontent.com/assets/595778/9863794/131125ae-5af8-11e5-9a51-13f0b0d5f809.png)

**Comment by davidrleonard** [comment]
Fixed in codeforamerica/cfawp2012@61ee349768aa4a96244626046c18f47746c36390
