### ISSUE TITLE
Need to add the word charitable to the website 

### ISSUE THREAD

**Issue by jessicasilverman** [codeforamerica/codeforamerica.org#1512]
Bottom tab currently says this: 
Code for America Labs, Inc is a non-partisan, non-political 501(c)(3) organization.

It needs to say this 
Code for America Labs, Inc is a non-partisan, non-political, 501(c)(3) charitable organization.

**Comment by davidrleonard** [comment]
Fixed!

**Comment by jessicasilverman** [comment]
thank you!
