### ISSUE TITLE
CSS fails to load on HTTPS (stylesheet is req'd via insecure method)

### ISSUE THREAD

**Issue by kuanb** [codeforamerica/codeforamerica.org#1526]
I was led to main site via click from some other site (I think Google). Either way, I ended up at `https://...`. Clicking on the "Blog" link from main page led to failed CSS library load on Blog page, since Blog page was trying to serve up relevant CSS via HTTP when site was being accessed via HTTPS.

![image](https://cloud.githubusercontent.com/assets/6053396/12083985/976cbd0c-b261-11e5-8dfc-643aa46d7809.png)

**Comment by kuanb** [comment]
Perhaps just check `window.location.protocol`?

**Comment by davidrleonard** [comment]
Thanks for the bug report! 

Fixed in codeforamerica/cfawp2012@95b7092623ff279f9dddfb978a50846d527c4674
