### ISSUE TITLE
Main nav spacing: CfA logo floats above nav

### ISSUE THREAD

**Issue by mollymcleod** [codeforamerica/codeforamerica.org#1529]
I think with the length of the nav, the CfA logo floats above it. 

![image](https://cloud.githubusercontent.com/assets/4099343/12103651/d48801f0-b2f8-11e5-9dde-40af031fb8e0.png)

**Comment by davidrleonard** [comment]
Fixed in 9794729a4b2fef8d861b1ab9e759aa1e21715260
