### ISSUE TITLE
PN training page redirects broken

### ISSUE THREAD

**Issue by ladyson** [codeforamerica/codeforamerica.org#218]
When I go to http://www.codeforamerica.org/about/peernetwork/

And click a link like the procurement training to http://www.codeforamerica.org/blog/07-02-2013/

I get this error: 

![screen shot 2014-02-21 at 3 44 15 pm](https://f.cloud.github.com/assets/1771715/2235954/2be6e2e2-9b52-11e3-971f-8a67d6377e2b.png)

**Comment by davidrleonard** [comment]
This seems fine now.
