### ISSUE TITLE
Pattern Portfolio or style.codeforamerica.org

### ISSUE THREAD

**Issue by danaoshiro** [codeforamerica/codeforamerica.org#251]
1. The map section of the patterns reads "{"message":"Account over limit."}"
2. Not sure if the nav-breadcrumb pattern is working properly. See image
![navbreadcrumb](https://f.cloud.github.com/assets/3669313/2328431/c0c57c5c-a3fe-11e3-9100-60def402d18e.jpg)

**Comment by davidrleonard** [comment]
We're not generating patterns like this anymore. The bugs referenced here no longer appear to be an issue/relevant.
