### ISSUE TITLE
Request from Meghan: Create a Job Feed to embed on the /jobs page

### ISSUE THREAD

**Issue by danaoshiro** [codeforamerica/codeforamerica.org#252]
In order to avoid having to add individual jobs, we'd like to embed a resumator job feed to the /jobs page.

**Comment by davidrleonard** [comment]
I experimented with this with @BrendaStone a bit back. We decided, for now, it's fine to add/remove jobs manually to keep fine-grained control over what we show on the /jobs/ page, vs. ceding control to Jazz on what info and style gets spit out onto our page.
