### ISSUE TITLE
Navbar changing size/position on scroll is jarring

### ISSUE THREAD

**Issue by lippytak** [codeforamerica/codeforamerica.org#277]
Here's the navbar when you're at the top of the page: 
![before](https://cloud.githubusercontent.com/assets/2533112/2574145/e08d7e94-b92b-11e3-9d06-36d78d5bd94c.png)

And here's the navbar when you scroll down: ![after](https://cloud.githubusercontent.com/assets/2533112/2574137/c0030b58-b92b-11e3-9b6b-ea4023d4a08b.png)

The size/location change is a bit jarring and hard to track. Consider keeping the navbar anchored at the top of the window at all times.

**Comment by davidrleonard** [comment]
We got rid of the sticky thing.
