### ISSUE TITLE
The list of Brigades on /geeks is imcomplete

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/codeforamerica.org#278]
#### Description
We're constantly adding new Brigades, and they are constantly updating their links to their websites. If only there was a way to constantly use the up to date information ...

Lets use the Civic Tech API! Let's populate the list below with content from the API.
![screen shot 2014-04-04 at 1 28 12 pm](https://cloud.githubusercontent.com/assets/595778/2620004/be353daa-bc37-11e3-8918-8d505bbfe5c3.png)

#### Tips
- [ ] Use javascript to grab the list of Brigades `http://codeforamerica.org/api/organizations`
- [ ] Make sure type == Brigade
- [ ] Replicate the style of the photo above

**Comment by davidrleonard** [comment]
No longer relevant, we don't list them out anymore. User flow is to send people to the /brigade/ site to find local brigades.
