### ISSUE TITLE
Spam on 'commons' subdomain

### ISSUE THREAD

**Issue by daguar** [codeforamerica/codeforamerica.org#321]
Looks like a spambot has gotten into http://commons.codeforamerica.org. Found this via googling 'site:codeforamerica.org promptly':

![screen shot 2014-05-12 at 4 07 23 pm](https://cloud.githubusercontent.com/assets/994938/2951604/37c24a18-da2a-11e3-8a71-522c337167d3.png)

Example spam:
![screen shot 2014-05-12 at 4 06 24 pm](https://cloud.githubusercontent.com/assets/994938/2951599/18d6c2a0-da2a-11e3-8ecc-3eecf574914c.png)

Link: http://commons.codeforamerica.org/payday-loans-share-cash-promptly-without-faxing-files

**Comment by davidrleonard** [comment]
Commons no longer exists.
