### ISSUE TITLE
CfA logo is cut off at top of donate now page

### ISSUE THREAD

**Issue by monfresh** [codeforamerica/codeforamerica.org#326]
1. Go to https://secure.codeforamerica.org/page/contribute/default
2. Observe chopped off logo in top left:

![chopped off CfA logo on donate page](http://cl.ly/image/33240c1U2w3i/Image%202014-05-22%20at%202.13.12%20PM.png)

**Comment by davidrleonard** [comment]
There are other problems with that donate page, but this is not one.
