### ISSUE TITLE
Resolve text size differences in bio snippets & people pages

### ISSUE THREAD

**Issue by danaoshiro** [codeforamerica/codeforamerica.org#40]
From Cyd: I'm not famous for my great eye, but to me the text styling for people cards in the pattern library looks different from how it comes out on the actual built version. Smaller type size and correspondingly smaller line spacing - the pattern library version looks much better to me (in particular the centering works better); do you see the same thing & can you tell what's going on?

**Comment by davidrleonard** [comment]
No longer an issue, the small profile cards are working fine for us.
