### ISSUE TITLE
datasets that Code for America apps use?

### ISSUE THREAD

**Issue by mishymishyme** [codeforamerica/codeforamerica.org#434]
Hi folks, wondering if CfA tries to ensure that the apps built by fellows and other civic hackers employ datasets that are open?  Or are there instances where the data hasn't been released into the wild yet is used in the software development?  Do you folks have a CfA policy about this?  tx for all your work!

**Comment by davidrleonard** [comment]
@mishymishyme You pinged a long time ago... sorry nobody ever got back to you.

We do use open data in many of our apps, and advocate for its publication by government agencies. Learn more about our open government practices at http://codeforamerica.org/practices/open.

Sometimes we do develop software that interacts with data that hasn't been or can't be published openly — for example, when privacy laws would prevent or severely complicate publication, or when governments don't have the capacity to regularly publish a certain dataset. 

We don't have a hard and fast policy on this, but emphasize the publication and use of open data as a good thing to do in civic technology software projects.

Hope this belated answer helps.
