### ISSUE TITLE
Style issue: The badges on front page aren't correct

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/codeforamerica.org#452]
#### Description
The front page has some badges above the stats.
![screen shot 2014-07-20 at 4 06 02 pm](https://cloud.githubusercontent.com/assets/595778/3638819/8bf94b68-1062-11e4-9bf7-93f0384401d4.png)

The css shows that we were trying to load other badges though - glasses, etc.
![screen shot 2014-07-20 at 4 06 14 pm](https://cloud.githubusercontent.com/assets/595778/3638822/b0039310-1062-11e4-85ab-4b9da3722fab.png)

Our style guide shows how to get other badges, but they aren't working!
http://style.codeforamerica.org/?url=/patterns/badge-headings.html

I can't get the other badges besides rocket and octocat to load either.

**Comment by davidrleonard** [comment]
Looks like this is no longer an issue.
