### ISSUE TITLE
Honolulu Answers is no longer in use

### ISSUE THREAD

**Issue by rcackerman** [codeforamerica/codeforamerica.org#593]
Honolulu has discontinued Honolulu Answers. Might want to get rid of the link.

http://www.codeforamerica.org/apps/honolulu-answers/

**Comment by buckleytom** [comment]
this link still points to a site thats no longer active. also, naively, i would have expected this link to be somewhere here:

https://github.com/codeforamerica/codeforamerica.org/blob/master/apps/honolulu-answers/index.html

instead, i searched for it and found it here:

https://github.com/codeforamerica/codeforamerica.org/blob/a8f135845e7c2725733c8d1ba2a2d1d1e4e55f37/_includes/apps/honolulu-answers.html#L39
