### ISSUE TITLE
The "Every Year" banner is hard to read on main page

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/codeforamerica.org#605]
#### Description
The random front pages that come up are great. The one that begins "Every Year" is hard to read though. Its white letters on white letters.

#### Reproduce
Keep refreshing until you see it
![screen shot 2014-09-04 at 5 54 31 pm](https://cloud.githubusercontent.com/assets/595778/4159030/9eea45d4-3497-11e4-808a-f97ad9008641.png)

#### Files
https://github.com/codeforamerica/codeforamerica.org/blob/master/stories.js

**Comment by AnneAndrees** [comment]
I think this picture is not used any more.
