### ISSUE TITLE
A mechanism for alerting style users of version bumps

### ISSUE THREAD

**Issue by daguar** [codeforamerica/codeforamerica.org#707]
@phae asked me to add this. I encountered breakage recently (I had used pre-version URL implementation), so it would be good to have some system to track and alert users.

**Comment by phae** [comment]
The pattern portfolio has now been pulled out of this repo. As such, it'll be easier to answer this issue. I've moved it to the correct repo, though. Track that if you want to follow-up. https://github.com/codeforamerica/pattern-library/issues/1
