### ISSUE TITLE
Button hover on last button is off

### ISSUE THREAD

**Issue by maya** [codeforamerica/codeforamerica.org#743]
It fills the whole container the button is in
![screen shot 2014-10-27 at 10 24 58 am](https://cloud.githubusercontent.com/assets/5249443/4796322/af8b77f2-5e02-11e4-83a1-fe5376f5631c.png)

**Comment by davidrleonard** [comment]
@maban you still around by chance? :)

I've investigated this more, it appears we have a style that matches *button* with a hover on it that's super hard to override. Suggestions welcome.
