### ISSUE TITLE
Link stuck in a loop

### ISSUE THREAD

**Issue by mattboitan0** [codeforamerica/codeforamerica.org#791]
http://www.codeforamerica.org/about/values/#

The Join us link at the bottom of the page doesn't go anywhere

**Comment by davidrleonard** [comment]
@ZoeBlumenfeld or @Jaime-Alexis, any idea where this 'Join Us' link should point to?

**Comment by ZoeBlumenfeld** [comment]
For now I would say here http://www.codeforamerica.org/geeks/ @davidrleonard.

**Comment by Jaime-Alexis** [comment]
Yes though the Fellowship application information on that page is out of
date (towards the bottom).

--------------------------------------------------------------------------------------------------------------------------------
Jaime-Alexis Fowler | Director of Marketing | *Code for America*
<http://codeforamerica.org/> | p:*214.673.9060* | @JaimeAlexis
<http://www.twitter.com/JaimeAlexis>

*Bring the Code for America Fellowship to your city in 2016. Learn how.
<http://www.codeforamerica.org/governments/fellowship/>*

**Comment by davidrleonard** [comment]
I just removed the link.
