### ISSUE TITLE
Correct Wufoo form on 'Data Formats' page for OpenReferral

### ISSUE THREAD

**Issue by greggish** [codeforamerica/codeforamerica.org#823]
On this page: www.codeforamerica.org/our-work/data-formats/openreferral/
The wufoo form still has PLATS language baked into it.

It doesn't get used much but I just got this:

On Thu, Dec 4, 2014 at 10:33 AM, Wufoo <no-reply@wufoo.com> wrote:
Name	
Karl Nicholas
City	
San Francisco
State	
California
Email	karl.nicholas@outlook.com
How can we help? Let us know how you would like to get involved.	
I don't own the data, but I want tools to advocate for **PLATS** in my region
I want to participate in the Request for Comment period
Join webinar on how to implement **PLATS**

**Comment by davidrleonard** [comment]
Looking at the form, i don't see PLATS mentioned anymore. Correct me if I'm wrong.
