### ISSUE TITLE
Padding on layouts within layouts

### ISSUE THREAD

**Issue by maya** [codeforamerica/codeforamerica.org#843]
When we have two layouts wrapped inside each other, the padding of the outer layout is not visible. There is supposed to be 3em padding above and below the outer container, but when there is an inner container you don't see that padding and it's not in the middle. Is this behavior intended? /cc @maban 

![screen shot 2014-12-23 at 10 35 08 am](https://cloud.githubusercontent.com/assets/5249443/5541592/ff45f074-8a8f-11e4-9581-700ab1a98f80.png)

**Comment by davidrleonard** [comment]
@maban Revisiting this. Thoughts on using the clearfix vs. adding an overflow hidden to the layout classes?

**Comment by maban** [comment]
I don't like adding overflow:hidden on stuff because you often get content cut off. That's especially true if you're using it on any layout classes because you never know what's content might go inside them. Clearfix is a much safer route imo.
