### ISSUE TITLE
Broken link to capabilities

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/codeforamerica.org#870]
On http://www.codeforamerica.org/about/values/ there is a broken link to http://www.codeforamerica.org/governments/capabilities/ when it should probably be to http://www.codeforamerica.org/governments/principles/

I bring it up here instead of fixing it to say we should probably do a search and replace.

**Comment by bengolder** [comment]
just hit this bug while looking for the principles

**Comment by davidrleonard** [comment]
Good finds. Anything /capabilities/ or /principles/ now goes to /practices/ as of #1477. We change the name of those things a lot. :)
