### ISSUE TITLE
Name misspelled on the site

### ISSUE THREAD

**Issue by dharmishta** [codeforamerica/codeforamerica.org#875]
@davidrleonard 
My name is spelled incorrectly on this page: http://jekit.codeforamerica.org/codeforamerica/codeforamerica.org/speaker-content/speakers/

and additionally on this page (only spelled wrong once) http://jekit.codeforamerica.org/codeforamerica/codeforamerica.org/speaker-content/speakers/dharmishta-rood/

I can't figure out how to change it — I've looked in the obvious places here on Github. 

The correct spelling is Dharmishta

and the incorrect spelling ends with "tha"

**Comment by davidrleonard** [comment]
Fixed in #885.
