### ISSUE TITLE
Edit to Bracy speaker bio

### ISSUE THREAD

**Issue by cbracy** [codeforamerica/codeforamerica.org#887]
On http://www.codeforamerica.org/speakers/ Bracy's bio currently reads:

Catherine oversees Code for America’s civic engagement efforts. She a product manager and director of the Obama campaign’s 2012 technology field office in San Francisco.

Should read:

Catherine oversees Code for America’s civic engagement efforts. She was director of the Obama campaign’s 2012 technology field office in San Francisco.

(If there isn't a character restriction I would also add "prior to joining Code for America" at the beginning of the second sentence.

**Comment by davidrleonard** [comment]
Finished a bit back, thanks @cbracy.
