### ISSUE TITLE
Add hyperlink to FAQ from Fellowship page?  + Change Word Cities in "How are Cities Selected"

### ISSUE THREAD

**Issue by Ldskywalker79** [codeforamerica/codeforamerica.org#889]
1 ) This page doesn't indicate anywhere they can get to FAQ. I am having a hard time figuring out how folks know to find the FAQ page?  http://www.codeforamerica.org/governments/fellowship/

2) Also, we should change Cities to Governments in the section that says "How are Cities Selected"

PS.... sorry if I am not using this function right.... trying to be better about using/jumping into Git.

**Comment by davidrleonard** [comment]
Thanks @Ldskywalker79, all fixed.
