### ISSUE TITLE
Make root/2015-city-name redirect to city page

### ISSUE THREAD

**Issue by davidrleonard** [codeforamerica/codeforamerica.org#891]
For 2015 cities, this redirect should work:

    codeforamerica.org/indianapolis --> codeforamerica.org/governments/indianapolis
    codeforamerica.org/vallejo --> codeforamerica.org/governments/vallejo
    etc...

**Comment by migurski** [comment]
Maybe `http://c4a.me/{city name}` is a more appropriate avenue for this? What you’re describing is really a short link.

**Comment by migurski** [comment]
(oops, didn’t mean to close-n-comment)

**Comment by davidrleonard** [comment]
Sounds good to me, @migurski.
