### ISSUE TITLE
blog redirects are resolving to the blog's front page

### ISSUE THREAD

**Issue by tmaybe** [codeforamerica/codeforamerica.org#914]
http://www.codeforamerica.org/author/jen/ should redirect to http://www.codeforamerica.org/blog/author/jen/ but it resolves to http://www.codeforamerica.org/blog instead.

See the rules here: https://github.com/codeforamerica/codeforamerica.org/blob/25e16827e393b9ecf6c99de9c931b6ca70c4cd94/.htaccess#L99

Same thing happens with codeforamerica.org/category/..., etc.

**Comment by migurski** [comment]
I see the error; all those `$2`’s in the blog rules should be `$1`’s. Unsure why this wasn’t part of the unit tests, will need to add.

**Comment by davidrleonard** [comment]
Looks like this was fixed, the redirects resolve correctly now.
