### ISSUE TITLE
Add marketing dashboard to README, possibly to site

### ISSUE THREAD

**Issue by davidrleonard** [codeforamerica/codeforamerica.org#918]
We have a cool dashboard. Let's show it to people.

//cc @ZoeBlumenfeld

**Comment by Jaime-Alexis** [comment]
Definitely pro-dashboard; have a few questions about Ducksboard data.

--------------------------------------------------------------------------------------------------------------------------------
Jaime-Alexis Fowler | Director of Marketing | *Code for America*
<http://codeforamerica.org/> | p:*214.673.9060* | @JaimeAlexis
<http://www.twitter.com/JaimeAlexis>

*Bring the Code for America Fellowship to your city in 2016. Learn how.
<http://www.codeforamerica.org/governments/fellowship/>*

**Comment by migurski** [comment]
Put it on the [office screens](http://github.com/codeforamerica/office-screen/pull/18).

**Comment by davidrleonard** [comment]
We did as @migurski recommended.
