### ISSUE TITLE
Add new section to /our-work/initiatives/ landing page for Talent initiative

### ISSUE THREAD

**Issue by davidrleonard** [codeforamerica/codeforamerica.org#920]
We have a new initiative! The Talent initiative page lives at http://codeforamerica.org/our-work/initiatives/talent. The [initiatives landing page](http://codeforamerica.org/our-work/initiatives/talent) should have a nice little section for it.

@lanebecker flagging for the future.

**Comment by lanebecker** [comment]
I'll get on that ASAP.
