### ISSUE TITLE
Email signup looks weird on blog and brigade pages

### ISSUE THREAD

**Issue by migurski** [codeforamerica/codeforamerica.org#936]
See https://www.codeforamerica.org/blog/, http://www.codeforamerica.org/brigade/, http://www.codeforamerica.org/library/, and other places where global-footer is used.

![footer](https://cloud.githubusercontent.com/assets/58730/6198825/57373e78-b3d0-11e4-921c-f5c2904cbe8b.png)

**Comment by migurski** [comment]
I recommend sticking to CSS from the pattern portfolio, adding new CSS to the pattern portfolio, or ensuring that this HTML appears outside the global footer.

**Comment by davidrleonard** [comment]
Fixed in #952. Working with @ondrae on improving this.
