### ISSUE TITLE
Remove current recruitment for Safety/Justice lead from Focus area page

### ISSUE THREAD

**Issue by Ldskywalker79** [codeforamerica/codeforamerica.org#943]
This page still shows that we're recruitng for a FA lead http://www.codeforamerica.org/our-work/focus-areas/

**Comment by Jaime-Alexis** [comment]
Sure, I can remove. I'm going to flag this for @RebeccaCoelius & @migurski as they're leading on the hires I believe and can keep this updated going forward as things progress with the Econ Dev.

**Comment by Jaime-Alexis** [comment]
Just removed the hire for S&J. @jmadans looks like you're still the contact on this page for the focus areas & @alanjosephwilliams we're missing links to the new health page. Did you and @davidrleonard talk about how to organize?

**Comment by davidrleonard** [comment]
This was fixed in #951.
