### ISSUE TITLE
Bad URI builder

### ISSUE THREAD

**Issue by scott-joe-williams** [codeforamerica/codeforamerica.org#945]
After registering for the Brigade, I was lead to a [thank-you page](http://www.codeforamerica.org/brigade/thank-you?source=no_brigade) with a broken link.

![screen shot 2015-02-21 at 1 36 51 pm](https://cloud.githubusercontent.com/assets/2026866/6315403/bbfb0a70-b9ce-11e4-863b-7fe8d08cdd5c.png)

**Comment by ondrae** [comment]
Sorry about that, fixed it.
