### ISSUE TITLE
Broken Link on Button

### ISSUE THREAD

**Issue by scott-joe-williams** [codeforamerica/codeforamerica.org#947]
src: [codeforamerica.org/geeks/our-geeks/brigade-captains/index.html](https://github.com/codeforamerica/codeforamerica.org/blob/3276525cdc1ebb1cb3b0b283712e479b6048bec2/geeks/our-geeks/brigade-captains/index.html#L32)
Contains a broken link on the "Become a Captain" button [[prod](http://www.codeforamerica.org/geeks/our-geeks/brigade-captains/)].

**Comment by ondrae** [comment]
Thanks for pointing this out @scott-joe-williams
