### ISSUE TITLE
Please create an anchor tag on codeforamerica.org/summit next to the Register header

### ISSUE THREAD

**Issue by mattboitan0** [codeforamerica/codeforamerica.org#960]
Would be so much easier for us to direct people to register.

**Comment by davidrleonard** [comment]
Great idea, here it is: http://www.codeforamerica.org/summit/#register

**Comment by mattboitan0** [comment]
Thanks!

On Wed, Mar 11, 2015 at 11:40 AM, David Leonard <notifications@github.com>
wrote:

> Great idea, here it is: http://www.codeforamerica.org/summit/#register
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/codeforamerica.org/issues/960#issuecomment-78342520>
> .
>



-- 
Matt Boitano
Development Coordinator
Code for America <http://codeforamerica.org>

O: 415.233.8996 | LinkedIn <http://linkedin.com/in/mattboitano> |
@mattboitan0 <https://twitter.com/mattboitan0>

*Join me at the 2015 Code for America Summit,
<http://www.codeforamerica.org/summit/?source_codes=staff> **September 30*
*–**October 2.*
