### ISSUE TITLE
remove weird screenshot appearing on Open Data Playbook

### ISSUE THREAD

**Issue by dschrimmer** [codeforamerica/codeforamerica.org#978]
funky Chicago screenshot under "Internal Costs Savings and Efficiency" section; San Francisco Crime Spotting Map formatting weird under "public safety" 

www.codeforamerica.org/governments/principles/open-data/#success-stories

I was able to fix other things in the playbook, but would love some help from someone smarter than me ( @phae  @migurski @davidrleonard @dan) to make those final changes. Thanks!

**Comment by danhon** [comment]
Well, it's better than it was before, but now I can't work out why the header for the Crimespotting entry is centered.
