### ISSUE TITLE
/governments/capabilities page not found

### ISSUE THREAD

**Issue by alanjosephwilliams** [codeforamerica/codeforamerica.org#985]
![image](https://cloud.githubusercontent.com/assets/2983464/6760038/528b7838-cf02-11e4-9f83-a14078a263e7.png)

**Comment by alanjosephwilliams** [comment]
Navigated to from "new way of working" on http://www.codeforamerica.org/about/values/

**Comment by davidrleonard** [comment]
Links fixed once and for all in bb5f3f21df3343123cae8e0de465987a6c1a6564, redirects sitewide from .*/capabilities/.* to /practices/ implemented in #1477.
