### ISSUE TITLE
Gov Application Page 

### ISSUE THREAD

**Issue by Ldskywalker79** [codeforamerica/codeforamerica.org#988]
couldn't submit when I put large amounts of text in the text Box. We need to flag if there is a word limit.

**Comment by Ldskywalker79** [comment]
@davidrleonard Any luck on this?

**Comment by Ldskywalker79** [comment]
Also, just wondering if you saw the comments about the thank you page going to a white portion under the actual thank you text, and wondering if we can fix that so people know they actually submitted their application.

**Comment by davidrleonard** [comment]
Fixed in #992. We're redirecting off-site to the Google Form for now to alleviate these issues.
