### ISSUE TITLE
No primer peso project page

### ISSUE THREAD

**Issue by arouault** [codeforamerica/codeforamerica.org#989]
There is no primer peso project page in english. All links redirect to site itself in spanish. Here's the about text that was never implemented: http://docs.primerpeso.org/additional_docs/cfa_apps_page.html

**Comment by arouault** [comment]
(not sure if it's meant to be an app or a project -- either way, there isn't one) :)

**Comment by cydharrell** [comment]
working on a whole stream of this type of stuff with @dschrimmer & @danhon here https://github.com/codeforamerica/content-team/issues/89

**Comment by davidrleonard** [comment]
We have a page! http://codeforamerica.org/focus/economic-development/primerpeso
